# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hospital_pb2 as hospital__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hospital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthorizationServiceStub:
    """============ AUTHORIZATION SERVICE ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAccess = channel.unary_unary(
                '/hospital.AuthorizationService/CheckAccess',
                request_serializer=hospital__pb2.AccessRequest.SerializeToString,
                response_deserializer=hospital__pb2.AccessResponse.FromString,
                _registered_method=True)


class AuthorizationServiceServicer:
    """============ AUTHORIZATION SERVICE ============
    """

    def CheckAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAccess,
                    request_deserializer=hospital__pb2.AccessRequest.FromString,
                    response_serializer=hospital__pb2.AccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.AuthorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.AuthorizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthorizationService:
    """============ AUTHORIZATION SERVICE ============
    """

    @staticmethod
    def CheckAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.AuthorizationService/CheckAccess',
            hospital__pb2.AccessRequest.SerializeToString,
            hospital__pb2.AccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PatientDataServiceStub:
    """============ PATIENT DATA SERVICE ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientsByCaregiver = channel.unary_unary(
                '/hospital.PatientDataService/GetPatientsByCaregiver',
                request_serializer=hospital__pb2.CaregiverRequest.SerializeToString,
                response_deserializer=hospital__pb2.PatientListResponse.FromString,
                _registered_method=True)
        self.GetPatientSummary = channel.unary_unary(
                '/hospital.PatientDataService/GetPatientSummary',
                request_serializer=hospital__pb2.PatientRequest.SerializeToString,
                response_deserializer=hospital__pb2.RawPatientDataResponse.FromString,
                _registered_method=True)
        self.GetPatientHistory = channel.unary_unary(
                '/hospital.PatientDataService/GetPatientHistory',
                request_serializer=hospital__pb2.PatientRequest.SerializeToString,
                response_deserializer=hospital__pb2.RawPatientDataResponse.FromString,
                _registered_method=True)
        self.GetAggregatedStats = channel.unary_unary(
                '/hospital.PatientDataService/GetAggregatedStats',
                request_serializer=hospital__pb2.CohortRequest.SerializeToString,
                response_deserializer=hospital__pb2.AggregatedStatsResponse.FromString,
                _registered_method=True)
        self.StreamCohortData = channel.unary_stream(
                '/hospital.PatientDataService/StreamCohortData',
                request_serializer=hospital__pb2.CohortRequest.SerializeToString,
                response_deserializer=hospital__pb2.RawPatientDataResponse.FromString,
                _registered_method=True)


class PatientDataServiceServicer:
    """============ PATIENT DATA SERVICE ============
    """

    def GetPatientsByCaregiver(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregatedStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCohortData(self, request, context):
        """Server streaming: stream cohort patients one at a time instead of
        buffering the whole cohort in memory (useful for large coortes).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientsByCaregiver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientsByCaregiver,
                    request_deserializer=hospital__pb2.CaregiverRequest.FromString,
                    response_serializer=hospital__pb2.PatientListResponse.SerializeToString,
            ),
            'GetPatientSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientSummary,
                    request_deserializer=hospital__pb2.PatientRequest.FromString,
                    response_serializer=hospital__pb2.RawPatientDataResponse.SerializeToString,
            ),
            'GetPatientHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientHistory,
                    request_deserializer=hospital__pb2.PatientRequest.FromString,
                    response_serializer=hospital__pb2.RawPatientDataResponse.SerializeToString,
            ),
            'GetAggregatedStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregatedStats,
                    request_deserializer=hospital__pb2.CohortRequest.FromString,
                    response_serializer=hospital__pb2.AggregatedStatsResponse.SerializeToString,
            ),
            'StreamCohortData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCohortData,
                    request_deserializer=hospital__pb2.CohortRequest.FromString,
                    response_serializer=hospital__pb2.RawPatientDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.PatientDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.PatientDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientDataService:
    """============ PATIENT DATA SERVICE ============
    """

    @staticmethod
    def GetPatientsByCaregiver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.PatientDataService/GetPatientsByCaregiver',
            hospital__pb2.CaregiverRequest.SerializeToString,
            hospital__pb2.PatientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.PatientDataService/GetPatientSummary',
            hospital__pb2.PatientRequest.SerializeToString,
            hospital__pb2.RawPatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.PatientDataService/GetPatientHistory',
            hospital__pb2.PatientRequest.SerializeToString,
            hospital__pb2.RawPatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAggregatedStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.PatientDataService/GetAggregatedStats',
            hospital__pb2.CohortRequest.SerializeToString,
            hospital__pb2.AggregatedStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCohortData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hospital.PatientDataService/StreamCohortData',
            hospital__pb2.CohortRequest.SerializeToString,
            hospital__pb2.RawPatientDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataTransformServiceStub:
    """============ DATA TRANSFORM SERVICE ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ToFHIRPatient = channel.unary_unary(
                '/hospital.DataTransformService/ToFHIRPatient',
                request_serializer=hospital__pb2.TransformRequest.SerializeToString,
                response_deserializer=hospital__pb2.FHIRResource.FromString,
                _registered_method=True)
        self.ToFHIRBundle = channel.unary_unary(
                '/hospital.DataTransformService/ToFHIRBundle',
                request_serializer=hospital__pb2.TransformBundleRequest.SerializeToString,
                response_deserializer=hospital__pb2.FHIRBundle.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_unary(
                '/hospital.DataTransformService/Aggregate',
                request_serializer=hospital__pb2.RawCohortDataResponse.SerializeToString,
                response_deserializer=hospital__pb2.AggregatedStatsResponse.FromString,
                _registered_method=True)
        self.CollectFHIRBundle = channel.stream_unary(
                '/hospital.DataTransformService/CollectFHIRBundle',
                request_serializer=hospital__pb2.TransformRequest.SerializeToString,
                response_deserializer=hospital__pb2.FHIRBundle.FromString,
                _registered_method=True)
        self.TransformPipeline = channel.stream_stream(
                '/hospital.DataTransformService/TransformPipeline',
                request_serializer=hospital__pb2.TransformRequest.SerializeToString,
                response_deserializer=hospital__pb2.FHIRResource.FromString,
                _registered_method=True)


class DataTransformServiceServicer:
    """============ DATA TRANSFORM SERVICE ============
    """

    def ToFHIRPatient(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToFHIRBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectFHIRBundle(self, request_iterator, context):
        """Client streaming: gateway streams raw patients (e.g. consumed from
        PatientDataService.StreamCohortData) and gets back one consolidated bundle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformPipeline(self, request_iterator, context):
        """Bidirectional streaming: pipeline mode used during load tests — raw
        patients go in, transformed FHIR resources come out, one at a time,
        without waiting for the whole batch (keeps latency low under load).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataTransformServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ToFHIRPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.ToFHIRPatient,
                    request_deserializer=hospital__pb2.TransformRequest.FromString,
                    response_serializer=hospital__pb2.FHIRResource.SerializeToString,
            ),
            'ToFHIRBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.ToFHIRBundle,
                    request_deserializer=hospital__pb2.TransformBundleRequest.FromString,
                    response_serializer=hospital__pb2.FHIRBundle.SerializeToString,
            ),
            'Aggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=hospital__pb2.RawCohortDataResponse.FromString,
                    response_serializer=hospital__pb2.AggregatedStatsResponse.SerializeToString,
            ),
            'CollectFHIRBundle': grpc.stream_unary_rpc_method_handler(
                    servicer.CollectFHIRBundle,
                    request_deserializer=hospital__pb2.TransformRequest.FromString,
                    response_serializer=hospital__pb2.FHIRBundle.SerializeToString,
            ),
            'TransformPipeline': grpc.stream_stream_rpc_method_handler(
                    servicer.TransformPipeline,
                    request_deserializer=hospital__pb2.TransformRequest.FromString,
                    response_serializer=hospital__pb2.FHIRResource.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.DataTransformService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.DataTransformService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataTransformService:
    """============ DATA TRANSFORM SERVICE ============
    """

    @staticmethod
    def ToFHIRPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.DataTransformService/ToFHIRPatient',
            hospital__pb2.TransformRequest.SerializeToString,
            hospital__pb2.FHIRResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToFHIRBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.DataTransformService/ToFHIRBundle',
            hospital__pb2.TransformBundleRequest.SerializeToString,
            hospital__pb2.FHIRBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.DataTransformService/Aggregate',
            hospital__pb2.RawCohortDataResponse.SerializeToString,
            hospital__pb2.AggregatedStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectFHIRBundle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hospital.DataTransformService/CollectFHIRBundle',
            hospital__pb2.TransformRequest.SerializeToString,
            hospital__pb2.FHIRBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformPipeline(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hospital.DataTransformService/TransformPipeline',
            hospital__pb2.TransformRequest.SerializeToString,
            hospital__pb2.FHIRResource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
