apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: grupo-6
type: Opaque
stringData:
  POSTGRES_DB: pseudopep_g06
  POSTGRES_USER: grupo06_user
  POSTGRES_PASSWORD: "123@g06"
  DATABASE_URL: "host=192.168.122.1 port=5432 dbname=pseudopep_g06 user=grupo06_user password=123@g06"
