apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: hospital
type: Opaque
stringData:
  POSTGRES_DB: hospital
  POSTGRES_USER: hospital
  POSTGRES_PASSWORD: hospital
  DATABASE_URL: "host=postgres port=5432 dbname=hospital user=hospital password=hospital"
